name: CI

on:
  pull_request:

env:
  HUSKY: 0
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # to be able to publish to GitHub Packages
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }} # Custom user with needed permissions
      - uses: will-bank/nx-set-shas-action@v1.0.0
      - uses: will-bank/pnpm-action-setup@v1.0.0
        with:
          version: 8.6.12
      - run: pnpm i --frozen-lockfile
      - run: pnpm dlx nx format:check
      - run: pnpm dlx nx affected -t lint --parallel=3
      - run: pnpm dlx nx affected -t test --parallel=3 --configuration=ci
      - run: pnpm dlx nx affected -t build --parallel=3
