name: semantic-release
run-name: Publishing new version
on:
  push:
    branches: [ main ]

env:
  HUSKY: 0
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Git
        run: |
          git config usre.name "Rabah Zeineddine"
          git config usre.email "rabah.zeineddine@hotmail.com"
      - uses: pnpm/action-setup@v2
        with:
          version: 8.6.12
      - run: pnpm i --frozen-lockfile
      - run: pnpm dlx nx affected -t build --parallel=3

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm dlx nx run-many --targets=build,semantic-release --parallel=false
