name: CI

on:
  push:
    branches:
      - main

env:
  HUSKY: 0
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }} # Custom user with needed permissions
      - name: Setup Git User
        run: |
          git config --global user.name "willbank-platforms"
          git config --global user.email "willbank-platforms@willbank.com.br"
      - run: npm ci
      - run: npx nx affected -t build --parallel=3

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx nx run-many --targets=build,release
