name: CI Release

on:
  push:
    branches:
      - main

env:
  HUSKY: 0
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
      packages: write # to be able to publish to GitHub Packages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }} # Custom user with needed permissions
      - name: Setup Git User
        run: |
          git config --global user.name "willbank-platforms"
          git config --global user.email "willbank-platforms@willbank.com.br"
      - uses: will-bank/pnpm-action-setup@v1.0.0
        with:
          version: 8.6.12
      - run: pnpm i --frozen-lockfile
      - run: npx nx affected -t build --parallel=3

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.WILLBANK_PLATFORMS_PERSONAL_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx nx run-many --targets=build,semantic-release --parallel=false
